# Generated by Django 4.2.9 on 2024-02-01 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='business',
        ),
        migrations.AddField(
            model_name='campaign',
            name='no_of_likes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='no_of_sales',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='no_of_visitors',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='logic.business')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='logic.product'),
            preserve_default=False,
        ),
    ]
